# Generated by Django 4.0.2 on 2022-03-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
