# Generated by Django 4.0.3 on 2022-03-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
    ]
