# Generated by Django 4.0.3 on 2022-03-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_image_post_thumbnail_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
