# Generated by Django 4.0.3 on 2022-03-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_alter_blogcomment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
